var resources = [
    {
        name: "plane",
        type: "image",
        src: "sprites/plane.png"
    }, {
        name: "Terrain",
        type: "image",
        src: "levels/tilesets/terrain.png"
    }, {
        name: "metatiles32x32",
        type: "image",
        src: "levels/tilesets/metatiles32x32.png"
    }, {
        name: "level1",
        type: "tmx",
        src: "levels/level1.tmx"
    }, {
        name: "sopwith_engineidle",
        type: "audio",
        src: "sounds/",
        channel: 1
    }, {
        name: "sopwith_engine0.2",
        type: "audio",
        src: "sounds/",
        channel: 1
    }, {
        name: "sopwith_engine0.3",
        type: "audio",
        src: "sounds/",
        channel: 1
    }, {
        name: "sopwith_engine0.4",
        type: "audio",
        src: "sounds/",
        channel: 1
    }, {
        name: "sopwith_engine0.5",
        type: "audio",
        src: "sounds/",
        channel: 1
    }, {
        name: "sopwith_engine0.6",
        type: "audio",
        src: "sounds/",
        channel: 1
    }, {
        name: "sopwith_engine0.7",
        type: "audio",
        src: "sounds/",
        channel: 1
    }, {
        name: "sopwith_engine0.8",
        type: "audio",
        src: "sounds/",
        channel: 1
    }, {
        name: "sopwith_engine0.9",
        type: "audio",
        src: "sounds/",
        channel: 1
    }, {
        name: "sopwith_engine1",
        type: "audio",
        src: "sounds/",
        channel: 1
    }


];
